# site settings
title: GTIA
subtitle: International Ambassadors at Georgia Tech
# Bringing the world to Georgia Tech and Georgia Tech to the world
email: gtinternationalambassadors@gmail.com
description: We bring the World to Georgia Tech and Georgia Tech to the World
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Georgia Institute of Technology
city: Atlanta
state: GA
zip_code:
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 20 # note that this tends to be higher than 3 since some pages don't display

# social settings
500px_url:
facebook_url: https://www.facebook.com/GTIAmbassadors/
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/gtiambassadors/
linkedin_url: https://www.linkedin.com/company/international-ambassadors-at-georgia-tech/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
